- src/interface/efi/efi_download.c
Claiming the SNP devices has the side effect of raising the TPL to
iPXE's normal operating level of TPL_CALLBACK (see the commit message
for c89a446 ("[efi] Run at TPL_CALLBACK to protect against UEFI
timers") for details).  This must happen before executing any code
that relies upon the TPL having been raised to TPL_CALLBACK.
The call to efi_snp_claim() in efi_download_start() currently happens
only after the call to xfer_open().  Calling xfer_open() will
typically result in a retry timer being started, which will result in
a call to currticks() in order to initialise the timer.  The call to
currticks() will drop to TPL_APPLICATION and restore to TPL_CALLBACK
in order to allow a timer tick to occur.  Since this call happened
before the call to efi_snp_claim(), the restored TPL is …
> [efi] Claim SNP devices early in efi_download_start()

- src/include/ipxe/asn1.h
Older versions of gcc (observed with gcc 4.5.3) require attributes to
be specified on the first declaration of a symbol, and will silently
ignore attributes specified after the initial declaration.  This
causes the ASN.1 OID-identified algorithms to end up misaligned.
Fix by adding __asn1_algorithm to the initial declarations in asn1.h.
Debugged-by: Dentcho Bankov <dbankov@vmware.com>
> [build] Fix building on older versions of gcc

- src/net/eth_slow.c
Some network topologies seem to cause LACP packets transmitted by iPXE
to be looped back as received packets.  Since iPXE's trivial LACP
responder will send one response per received packet, this results in
an immediate LACP packet storm.
Detect looped back LACP packets (based on the received LACP actor MAC
address), and refuse to respond to such packets.
Fixes: #157 
Reported-by: Tore Anderson <tore@fud.no>
> [lacp] Detect and ignore erroneously looped back LACP packets

- src/drivers/infiniband/arbel.c
- src/drivers/infiniband/flexboot_nodnic.c
- src/drivers/infiniband/golan.c
- src/drivers/infiniband/hermon.c
- src/drivers/infiniband/linda.c
- src/drivers/infiniband/qib7322.c
- src/include/ipxe/infiniband.h
- src/net/infiniband.c
- src/net/infiniband/ib_sma.c
Allow drivers to override total number of reported infiband ports. This is
required to report the correct number of total ports, on devices with dynamic
port types.
For example, dual-port Mellanox cards configured for (eth, ib) would be rejected
by the subnet manager, because they report using "port 2, out of 1".
Signed-off-by: Christian Iversen <ci@iversenit.dk>
> [infiniband] Require drivers to report the number of device ports

- src/image/embedded.c
iPXE when used as a NIC option ROM can sometimes be reloaded by the
UEFI/BIOS and any pre-initialised memory will remain loaded. When the
imgtrust command is run it sets `require_trusted_images'. Upon
reloading, iPXE tries to load the embedded script but fails as it is not
marked trusted. Setting this flag ensures that imgtrust with embedded
scripts is reentrant.
> [image] Implicitly trust first embedded image 

- src/drivers/infiniband/hermon.c
- src/drivers/infiniband/hermon.h
Some older versions of the hardware (and/or firmware) do not report an
event when an Infiniband link reaches the INIT state.  The driver
works around this missing event by calling ib_smc_update() on each
event queue poll while the link is in the DOWN state.
Commit 6cb12ee ("[hermon] Increase polling rate for command
completions") addressed this by speeding up the time taken to issue
each command invoked by ib_smc_update().  Experimentation shows that
the impact is still significant: for example, in a situation where an
unplugged port is opened, the throughput on the other port can be
reduced by over 99%.
Fix by throttling the rate at which link polling is attempted.
Debugged-by: Christian Iversen <ci@iversenit.dk>
> [hermon] Limit link poll frequency in DOWN state

- src/drivers/infiniband/hermon.h
The programming documentation states that the reset magic value is
"0x00000001 (Big Endian)", and the current code matches this by using
the value 0x01000000 for the implicitly little-endian writel().
Inspection of the FlexBoot source code reveals an exciting variety of
reset values, some suggestive of confusion around endianness.
Experimentation suggests that the value 0x01000001 works reliably
across a wide range of hardware.
Debugged-by: Christian Iversen <ci@iversenit.dk>
> [hermon] Use reset value suitable for ConnectX-3

- src/drivers/infiniband/hermon.c
- src/drivers/infiniband/hermon.h
Check for reset completion by waiting for the device to respond to PCI
configuration cycles, as documented in the Programmer's Reference
Manual.  On the original ConnectX HCA, this reduces the time spent on
reset from 1000ms down to 1ms.
> [hermon] Minimise reset time

- src/arch/x86/Makefile.pcbios
- src/arch/x86/scripts/prefixonly.lds
Some versions of GNU ld (observed with binutils 2.36 on Arch Linux)
introduce a .note.gnu.property section marked as loadable at a high
address and with non-empty contents.  This adds approximately 128MB of
garbage to the BIOS .usb disk images.
Fix by using a custom linker script for the prefix-only binaries such
as the USB disk partition table and MBR, in order to allow unwanted
sections to be explicitly discarded.
Reported-by: Christian Hesse <mail@eworm.de>
Tested-by: Christian Hesse <mail@eworm.de>
> [build] Work around stray sections introduced by some binutils versions

- src/arch/x86/prefix/rawprefix.S
Provide a generic raw image prefix, which assumes that the iPXE image
has been loaded in its entirety on a paragraph boundary.
> [prefix] Add a generic raw image prefix

- src/arch/x86/include/ipxe/cpuid.h
- src/arch/x86/transitions/librm.S
- src/arch/x86/transitions/librm_mgmt.c
Assume that preservation of the %xmm registers is unnecessary during
installation of iPXE into memory, since this is an operation that by
its nature substantially disrupts large portions of the system anyway
(such as the E820 memory map).  This assumption allows us to utilise
the existing CPUID code to check that FXSAVE/FXRESTOR are supported.
Test for support during the call to init_librm and store the flag for
use during subsequent calls to virt_call.
Reduce the scope of TIVOLI_VMM_WORKAROUND to affecting only the call
to check_fxsr(), to reduce #ifdef pollution in the remaining code.
> [librm] Test for FXSAVE/FXRESTOR instruction support

- src/Makefile.efi
- src/Makefile.housekeeping
- src/util/eficompress.c
- src/util/efirom.c
Use the reference implementation of the EFI compression algorithm
(taken from the EDK2 codebase, with minor bugfixes to allow
compilation with -Werror) to compress EFI ROM images.
Inspired-by: Laszlo Ersek <lersek@redhat.com>
> [efi] Compress EFI ROM images

- src/scripts/efi.lds
- src/util/elf2efi.c
As currently ELF sections rather than segments are converted to PE sections, PE section alignment is hard-coded, and some fields describing virtual properties are assigned values based on file alignment, EFI PE drivers generated by elf2efi are generally not well-aligned. This can cause issues when enforcing strict PE parsing rules (as I am currently proposing for EDK II / OVMF), or when enforcing section permissions.
This PR fixes all discovered issues regarding PE image alignment. Furthermore, the constructed debug and relocation sections are marked as discardable for security reasons. All changes made are in conformance with the PE specification.
The changes have been validated using a stricter EDK II image loader, with OVMF booting and successfully loading the appropriate EFI ROM. …
> [efi] Improve ELF to PE conversion

- src/drivers/net/intelxvf.c
Adding this missing identifier allows the X557-AT2 chipset
seen on (at least) Super Micro A2SDI-H-TF motherboards to
function with iPXE.
Signed-off-by: Tyler J. Stachecki <stachecki.tyler@gmail.com>
> intelxvf: Add additional PCI device ID to table

- src/util/genfsimg
Commit 79c0173 introduced the new genfsimg, which lacks the -l option when building ISO Files.
This option is required to build level 2 (long plain) ISO9660 Filenames, which are required when using 
the .lkrn extensions. Fixes #306
> [build] Fix genfsimg to build ISO with long filenames

- src/arch/x86/core/x86_bigint.c
- src/arch/x86/include/bits/bigint.h
The ARM versions of the big-integer inline assembly functions include
constraints to indicate that the output value is modified by the
assembly code.  These constraints are not present in the equivalent
code for the x86 versions.
As of GCC 11, this results in the compiler reporting that the output
values may be uninitialized.
Fix by including the relevant memory output constraints.
Reported-by: Christian Hesse <mail@eworm.de>
Fixes: #359
> [crypto] Add memory output constraints for big-integer inline assembly

- src/include/ipxe/rndis.h
Most RNDIS data structures include a trailing 4-byte reserved field.
For the REMOTE_NDIS_PACKET_MSG and REMOTE_NDIS_INITIALIZE_CMPLT
structures, this is an 8-byte field instead.
iPXE currently uses incorrect structure definitions with a 4-byte
reserved field in all data structures, resulting in data payloads that
overlap the last 4 bytes of the 8-byte reserved field.
RNDIS uses explicit offsets to locate any data payloads beyond the
message header, and so liberal RNDIS parsers (such as those used in
Hyper-V and in the Linux USB Ethernet gadget driver) are still able to
parse the malformed structures.
A stricter RNDIS parser (such as that found in some older Android
builds that seem to use an out-of-tree USB Ethernet gadget driver) may
reject the malformed structures since the data payload …
> [rndis] Fix size of reserved fields

- src/Makefile.housekeeping
Without this patch,
`BUILD_ID_CMD` used a checksum of `blib.a` that varied from mtimes
See https://reproducible-builds.org/ for why this matters.
This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
> [efi] Ensure build-id is deterministic

- src/core/uri.c
- src/include/ipxe/uri.h
- src/net/tcp/httpcore.c
- src/tests/uri_test.c
- src/usr/imgmgmt.c
iPXE decodes any percent-encoded characters during the URI parsing
stage, thereby allowing protocol implementations to consume the raw
field values directly without further decoding.
When reconstructing a URI string for use in an HTTP request line, the
percent-encoding is currently reapplied in a reversible way: we
guarantee that our reconstructed URI string could be decoded to give
the same raw field values.
This technically violates RFC3986, which states that "URIs that differ
in the replacement of a reserved character with its corresponding
percent-encoded octet are not equivalent".  Experiments show that
several HTTP server applications will attach meaning to the choice of
whether or not a particular character was percent-encoded, even when
the percent-encoding is unnecessary from the …
> [uri] Retain original encodings for path, query, and fragment fields

- src/core/settings.c
- src/include/ipxe/settings.h
- src/interface/smbios/smbios_settings.c
- src/tests/settings_test.c
The RFC4122 specification defines UUIDs as being in network byte
order, but an unfortunately significant amount of (mostly Microsoft)
software treats them as having the first three fields in little-endian
byte order.
In an ideal world, any server-side software that compares UUIDs for
equality would perform an endian-insensitive comparison (analogous to
comparing strings for equality using a case-insensitive comparison),
and would therefore not care about byte order differences.
Define a setting type name ":guid" to allow a UUID setting to be
formatted in little-endian order, to simplify interoperability with
server-side software that expects such a formatting.
> [settings] Support formatting UUIDs as little-endian GUIDs

- src/core/uri.c
- src/tests/uri_test.c
RFC3986 allows for colons to appear within the path component of a
relative URI, but iPXE will currently parse such URIs incorrectly by
interpreting the text before the colon as the URI scheme.
Fix by checking for valid characters when identifying the URI scheme.
Deliberately deviate from the RFC3986 definition of valid characters
by accepting "_" (which was incorrectly used in the iPXE-specific
"ib_srp" URI scheme and so must be accepted for compatibility with
existing deployments), and by omitting the code to check for
characters that are not used in any URI scheme supported by iPXE.
Fixes: #554
Reported-by: Ignat Korchagin <ignat@cloudflare.com>
> [uri] Allow for relative URIs that include colons within the path

- src/config/defaults/efi.h
AArch64 kernels tend to be distributed as gzip compressed images.
Enable IMAGE_GZIP by default for AArch64 to avoid the need for
uncompressed images to be provided.
Fixes: #585 
Originally-implemented-by: Alessandro Di Stefano <aleskandro@redhat.com>
> [efi] Enable IMAGE_GZIP by default for AArch64

- src/core/image.c
Embedded images do not have an associated URI.  This currently causes
the current working URI (cwuri) to be cleared when starting an
embedded image.
If the current working URI has been set via a ${next-server} setting
from a cached DHCP packet then this will result in unexpected
behaviour.  An attempt by the embedded script to use a relative URI to
download files from the TFTP server will fail with the error
Could not start download: Operation not supported (ipxe.org/3c092083)
Rerunning the "dhcp" command will not fix this error, since the TFTP
settings applicator will not see any change to the ${next-server}
setting and so will not reset the current working URI.
Fix by setting the current working URI to the image's URI only if the
image actually has an associated URI.
Debugged-by: Ignat …
> [image] Do not clear current working URI when executing embedded image

- src/net/udp/dns.c
We currently define the active DNS server as a global variable.  All
queries will start by attempting to contact the active DNS server, and
the active DNS server will be changed only if we fail to get a
response.  This effectively treats the DNS server list as expressing a
weak preference ordering: we will try servers in order, but once we
have found a working server we will stick with that server for as long
as it continues to respond to queries.
Some sites are misconfigured to hand out DNS servers that do not have
a consistent worldview.  For example: the site may hand out two DNS
server addresses, the first being an internal DNS server (which is
able to resolve names in private DNS domains) and the second being a
public DNS server such as 8.8.8.8 (which will correctly return
NXDOMAIN …
> [dns] Always start DNS queries using the first configured DNS server

- src/arch/x86/image/bzimage.c
bzimage_parse_cmdline() uses strcmp() to identify the named "vga=..." kernel command line option values, which will give a false negative if the option is not last on the command line.
Fix by temporarily changing the relevant command line separator (if any) to a NUL terminator.
Fixes: #777 
Debugged-by: Simon Rettberg <simon.rettberg@rz.uni-freiburg.de>
> [bzimage] Fix parsing of "vga=..." when not at end of command line

- src/include/ipxe/efi/efi_null.h
- src/include/ipxe/efi/efi_snp.h
- src/include/ipxe/vlan.h
- src/interface/efi/efi_null.c
- src/interface/efi/efi_snp.c
- src/net/vlan.c
UEFI implements VLAN support within the Managed Network Protocol (MNP)
driver, which may create child VLAN devices automatically based on
stored UEFI variables.  These child devices do not themselves provide
a raw-packet interface via EFI_SIMPLE_NETWORK_PROTOCOL, and may be
consumed only via the EFI_MANAGED_NETWORK_PROTOCOL interface.
The device paths constructed for these child devices may conflict with
those for the EFI_SIMPLE_NETWORK_PROTOCOL instances that iPXE attempts
to install for its own VLAN devices.  The upshot is that creating an
iPXE VLAN device (e.g. via the "vcreate" command) will fail if the
UEFI Managed Network Protocol has already created a device for the
same VLAN tag.
Fix by providing our own EFI_VLAN_CONFIG_PROTOCOL instance on the same
device handle as …
> EFI VLAN support

- src/arch/x86/interface/pcbios/bios_cachedhcp.c
- src/core/cachedhcp.c
- src/include/ipxe/cachedhcp.h
- src/include/ipxe/efi/efi_cachedhcp.h
- src/include/ipxe/efi/efi_path.h
- src/interface/efi/efi_cachedhcp.c
- src/interface/efi/efi_local.c
- src/interface/efi/efi_path.c
- src/interface/efi/efiprefix.c
When chainloading iPXE from a VLAN device, the MAC address within the cached DHCPACK will match the MAC address of the trunk device created by iPXE, and the cached DHCPACK will then end up being erroneously applied to the trunk device.  This tends to break outbound IPv4 routing, since both the trunk and VLAN devices will have the same assigned IPv4 address.
Fix by recording the VLAN tag along with the cached DHCPACK, and treating the VLAN tag as part of the filter used to match the cached DHCPACK against candidate network devices.
Also retain any unclaimed DHCPACK after startup to allow it to be matched against (and applied to) any device that gets created at runtime.
> VLAN support for cached DHCPACK

- src/drivers/net/ena.c
- src/drivers/net/ena.h
We currently don't allocate Asynchronous Event Notification Queues because we don't actually care about any of the events that may come in.
However, without allocating AENQ queues, ena internal memory checks fail and iPXE fails to run on Graviton systems.  So let's allocate the queues and not use them. That way, all target platforms will be happy.
With this patch applied, I can successfully run iPXE on c6g instances.
Signed-off-by: Alexander Graf <graf@amazon.com>
> [ena] Always allocate AENQ queues

- src/include/ipxe/efi/ProcessorBind.h
- src/util/elf2efi.c
We cannot rely on the EDK2 ProcessorBind.h headers when compiling a binary for execution on the build host itself (e.g. elf2efi), since the host's CPU architecture may not even be supported by EDK2.
Fix by skipping ProcessorBind.h when building a host binary, and defining the bare minimum required to allow other EDK2 headers to compile cleanly.
Fixes: #856 
Reported-by: Michal Suchánek <msuchanek@suse.de>
> [efi] Do not rely on ProcessorBind.h when building host binaries

- src/include/ipxe/tcp.h
The current maximum window size of 256kB was calculated based on rough link bandwidth and RTT measurements taken in 2012, and is too small to avoid filling the TCP window on some modern links.
Update the list of typical link bandwidth and RTT figures to reflect the modern world, and increase the maximum window size accordingly.
Fixes: #862 
> [tcp] Update maximum window size to 2MB

- src/include/ipxe/efi/efi_cmdline.h
- src/include/ipxe/errfile.h
- src/interface/efi/efi_cmdline.c
- src/interface/efi/efi_init.c
Treat a command line passed to iPXE via UEFI LoadOptions as an image to be registered at startup, as is already done for the .lkrn, .pxe, and .exe BIOS images.
Fixes: #721 
Originally-implemented-by: Ladi Prosek <lprosek@redhat.com>
> [efi] Accept a command line passed to an iPXE image via LoadOptions

- src/drivers/net/realtek.c
- src/drivers/net/realtek.h
Some cards seem to have the receive VLAN tag stripping feature enabled by default, which causes received VLAN packets to be misinterpreted as being received by the trunk device.
Fix by disabling VLAN tag stripping in the C+ Command Register.
Debugged-by: ?????? <yiyihu@gmail.com>
Tested-by: ?????? <yiyihu@gmail.com>
> [realtek] Explicitly disable VLAN offload

- src/drivers/bus/pci.c
- src/include/ipxe/pci.h
- src/interface/efi/efi_pci.c
The "bridge" driver introduced in 3aa6b79 ("[pci] Add minimal PCI bridge driver") is required only for BIOS builds using the ENA driver, where experimentation shows that we cannot rely on the BIOS to fully assign MMIO addresses.
Since the driver is a valid PCI driver, it will end up binding to all PCI bridge devices even on a UEFI platform, where the firmware is likely to have completed MMIO address assignment correctly.  This has no impact on most systems since there is generally no UEFI driver for PCI bridges: the enumeration of the whole PCI bus is handled by the PciBusDxe driver bound to the root bridge.
Experimentation shows that at least one laptop will freeze at the point that iPXE attempts to bind to the bridge device.  No deeper investigation has been carried out to find the root …
> [efi] Do not attempt to drive PCI bridge devices

- src/net/udp/dhcp.c
RFC 2131 leaves undefined the behaviour of the client in response to a DHCPNAK that comes from a server other than the selected DHCP server.
A substantial amount of online documentation suggests using multiple independent DHCP servers with non-overlapping ranges in the same subnet in order to provide some minimal redundancy.  Experimentation shows that in this setup, at least ISC dhcpd will send a DHCPNAK in response to the client's DHCPREQUEST for an address that is not within the range defined on that server.  (Since the requested address does lie within the subnet defined on that server, this will happen regardless of the "authoritative" parameter.)  The client will therefore receive a DHCPACK from the selected DHCP server along with one or more DHCPNAKs from each of the non-selected …
> [dhcp] Ignore DHCPNAK unless originating from the selected DHCP server

- src/config/config_ethernet.c
- src/config/general.h
- src/include/ipxe/errfile.h
- src/include/ipxe/if_ether.h
- src/include/ipxe/lldp.h
- src/net/lldp.c
Add support for recording LLDP packets and exposing TLV values via the settings mechanism.  LLDP settings are encoded as
`${netX.lldp/<prefix>.<type>.<index>.<offset>.<length>}`
where
`<type>` is the TLV type
`<offset>` is the starting offset within the TLV value
`<length>` is the length (or zero to read the from `<offset>` to the end)
`<prefix>`, if it has a non-zero value, is the subtype byte string of
length <offset> to match at the start of the TLV value, up to a
maximum matched length of 4 bytes
`<index>` is the index of the entry matching `<type>` and `<prefix>` to be
accessed, with zero indicating the first matching entry
The `<prefix>` is designed to accommodate both matching of the OUI within an organization-specific TLV (e.g. 0x0080c2 for IEEE 802.1 TLVs) and of a subtype byte …
> [lldp] Add support for the Link Layer Discovery Protocol

- src/drivers/bus/eisa.c
EISA expansion slot I/O port addresses overlap space that may be assigned to PCI devices, which can lead to register reads and writes with unwanted side effects during EISA probing.
Reduce the chances of performing EISA probing on PCI devices by probing EISA slot vendor and product ID registers only if the EISA system board vendor ID register indicates that the motherboard supports EISA.
Fixes: #877 
Debugged-by: Václav Ovsík <vaclav.ovsik@gmail.com>
Tested-by: Václav Ovsík <vaclav.ovsik@gmail.com>
> [eisa] Check for system board presence before probing for slots

- src/arch/x86/image/bzimage.c
- src/core/cpio.c
- src/core/image.c
- src/include/ipxe/image.h
The Linux kernel bzImage image format and the CPIO archive constructor will parse the image command line for certain arguments of the form "key=value".  This parsing is currently implemented using strstr() in a way that can cause a false positive suffix match.  For example, a command line containing "highmem=<n>" would erroneously be treated as containing a value for "mem=<n>".
Fix by centralising the logic used for parsing such arguments, and including a check that the argument immediately follows a whitespace delimiter (or is at the start of the string).
Fixes: #889 
> [image] Check delimiters when parsing command-line key-value arguments

- src/drivers/block/scsi.c
- src/include/ipxe/iscsi.h
- src/net/tcp/iscsi.c
We currently specify only the iSCSI default value for MaxBurstLength and ignore any negotiated value, since our internal block device API allows only for receiving directly into caller-allocated buffers and so we have no intrinsic limit on burst length.
A conscientious target may however refuse to attempt a transfer that we request for a number of blocks that would exceed the negotiated maximum burst length.
Fix by recording the negotiated maximum burst length and using it to limit the maximum number of blocks per transfer reported by the SCSI layer.
> [iscsi] Limit maximum transfer size to MaxBurstLength

- src/drivers/net/intelx.c
I called this one `82599-tn`/`82599 (TN)` based on the descriptions [here](https://pci-ids.ucw.cz/read/PC/8086/151c) and [here](https://www.flashrom.org/Supported_hardware#PCI_Devices), and followed the naming pattern for the other 82599 devices in this driver.
Tested with an Intel X520-T2 NIC.
> [intelx] Add PCI IDs for Intel 82599 10GBASE-T NIC

- src/drivers/net/intel.c
- src/drivers/net/intel.h
Hello, this fixes a weird hardware bug with I210s that I encountered. Basically not all the registers return to their default values on reset, so depending on how an OS is using the device it may become unable to pass traffic. I encountered this by using the QAV features on the I210 and then failing to get a DHCP address on the next boot after a reset signal was asserted.
More than happy to add explanation, testing logs, change up code, etc.
Using the current master branch, using the bin-x86_64-efi/ipxe.efi target:
```
FS0:\> master_ipxe.efi
iPXE initialising devices...ok
iPXE 1.21.1+ (g96bb6) -- Open Source Network Boot Firmware -- https://ipxe.org
Features: DNS HTTP iSCSI TFTP VLAN SRP AoE EFI Menu
iPXE> dhcp net1
Configuring (net1 00:17:3c:02:d6:7e).................. No configuration …
```
> Add workaround for I210 reset hardware bugs

- src/interface/efi/efi_veto.c
The EDK2 UefiPxeBcDxe driver includes some remarkably convoluted and unsafe logic in its driver binding protocol Start() and Stop() methods in order to support a pair of nominally independent driver binding protocols (one for IPv4, one for IPv6) sharing a single dynamically allocated data structure.  This PXEBC_PRIVATE_DATA structure is installed as a dummy protocol on the NIC handle in order to allow both IPv4 and IPv6 driver binding protocols to locate it as needed.
The error handling code path in the UefiPxeBcDxe driver's Start() method may attempt to uninstall the dummy protocol but fail to do so. This failure is ignored and the containing memory is subsequently freed anyway.  On the next invocation of the driver binding protocol, it will find and use this already freed block of …
> [efi] Veto the VMware UefiPxeBcDxe driver

- src/config/config.c
- src/config/defaults/efi.h
- src/config/settings.h
- src/include/ipxe/errfile.h
- src/interface/efi/efi_settings.c
EFI variables do not map neatly to the iPXE settings mechanism, since the EFI variable identifier includes a namespace GUID that cannot cleanly be supplied as part of a setting name.  Creating a new EFI variable requires the variable's attributes to be specified, which does not fit within iPXE's settings concept.
However, EFI variable names are generally unique even without the namespace GUID, and EFI does provide a mechanism to iterate over all existent variables.  We can therefore provide read-only access to EFI variables by comparing only the names and ignoring the namespace GUIDs.
Provide an "efi" settings block that implements this mechanism. Settings are returned as raw binary values by default since an EFI variable may contain boolean flags, integer values, ASCII strings, UCS-2 …
> [efi] Provide read-only access to EFI variables via settings mechanism

- src/core/interface.c
- src/core/xfer.c
- src/include/ipxe/interface.h
The interface debug message values constructed by INTF_DBG() et al rely on the interface being embedded within a containing object.  This assumption is not valid for the temporary outbound-only interfaces constructed on the stack by intf_shutdown() and xfer_vredirect().
Formalise the notion of a temporary outbound-only interface as having a NULL interface descriptor, and overload the "original interface descriptor" field to contain a pointer to the original interface that the temporary interface is shadowing.
Fixes: #982 
Originally-fixed-by: Vincent Fazio <vfazio@gmail.com>
> [interface] Fix debug message values for temporary interfaces

- src/core/parseopt.c
- src/include/ctype.h
- src/include/ipxe/keys.h
Commit 3ef4f7e ("[console] Avoid overlap between special keys and Unicode characters") renumbered the special key encoding to avoid collisions with Unicode key values outside the ASCII range.  This change broke backwards compatibility with existing scripts that specify key values using e.g. "prompt --key" or "menu --key".
Restore compatibility with existing scripts by tweaking the special key encoding so that the relative key value (i.e. the delta from KEY_MIN) is numerically equal to the old pre-Unicode key value, and by modifying parse_key() to accept a relative key value.
Reported-by: Sven Dreyer <sven@dreyer-net.de>
> [console] Restore compatibility with "--key" values in existing scripts

- src/drivers/bus/virtio-pci.c
vpm_ioread32() only reads 16-bit of data due to a copy and paste bug (using readw/inw like vpm_ioread16() instead of readl/inl). This causes the virtio-net driver of ipxe to fail with the virtio-net device emulation of VirtualBox because it is quite strict regarding register access width and alignment which must be the natural register width.
> virtio-pci.c: Fix implementation of vpm_ioread32()

- src/arch/x86/include/librm.h
We currently use "push $1f" within inline assembly to push the address of the real-mode code fragment, relying on the assembler to treat this as "pushl" for 32-bit code or "pushq" for 64-bit code.
As of binutils commit 5cc0077 ("x86: further adjust extend-to-32bit- address conditions"), first included in binutils-2.41, this implicit operand size is no longer calculated as expected and 64-bit builds will fail with
Error: operand size mismatch for `push'
Fix by adding an explicit operand size to the "push" instruction.
Fixes: #997 
Originally-fixed-by: Justin Cano <jstncno@gmail.com>
> [librm] Use explicit operand size when pushing a label address

- src/core/random.c
We currently use the number of timer ticks since power-on as a seed for the non-cryptographic RNG implemented by random().  Since iPXE is often executed directly after power-on, and since the timer tick resolution is generally low, this can often result in identical seed values being used on each cold boot attempt.
As of commit 41f786c ("[settings] Add "unixtime" builtin setting to expose the current time"), the current wall-clock time is always available within the default build of iPXE.  Use this time instead, to introduce variability between cold boot attempts on the same host. (Note that variability between different hosts is obtained by using the MAC address as an additional seed value.)
This has no effect on the separate DRBG used by cryptographic code.
Fixes: #1042 
Suggested-by: …
> [libc] Use wall clock time as seed for the (non-cryptographic) RNG

- src/include/ipxe/eap.h
- src/include/ipxe/eapol.h
- src/net/eap.c
- src/net/eapol.c
EAP exchanges may take a long time to reach a final status, especially when relying upon MAC Authentication Bypass (MAB).  Our current behaviour of sending EAPoL-Start every few seconds until a final status is obtained can prevent these exchanges from ever completing.
Fix by suppressing EAPoL-Start once EAP is in progress, and by limiting the total number of EAPoL-Start packets sent per authentication attempt.
Fixes: #1048
> Fix EAPoL-Start behaviour to allow slow authentication exchanges to succeed

- src/drivers/net/intel.c
Successfully tested on FUJITSU LIFEBOOK U7413.
> [intel] Add PCI ID for I219-LM (23)

- src/arch/x86/interface/pcbios/bios_smbios.c
- src/include/ipxe/smbios.h
- src/interface/smbios/smbios.c
Support scanning for the 64-bit SMBIOS3 entry point in addition to the 32-bit SMBIOS2 entry point.
Prefer use of the 32-bit entry point if present, since this is guaranteed to be within accessible memory.
Fixes: #1094
> [smbios] Support scanning for the 64-bit SMBIOS3 entry point

- src/.gitignore
- src/bin/.gitignore
- src/config/local/.gitignore
I ran into a problem after I cloned ipxe, then committed that tree to another repo, iPXE would not build in the new repo. I found it was because the bin and config/local directories were not committed in the new repo due to .gitignore rules. This PR updates the .gitignore rules so the required directories are not excluded when committing the tree.
> Fix .gitignore files so bin and local dirs are not lost

- src/arch/arm/interface/efi/efiarm_nap.c
- src/arch/loong64/interface/efi/efiloong64_nap.c
- src/arch/x86/interface/efi/efix86_nap.c
When ExitBootServices() invokes efi_shutdown_hook(), there may be nothing to generate an interrupt since the timer is disabled in the first step of ExitBootServices(). Additionally, for VMs OVMF masks everything from the PIC (except the timer) by default. This means that calling cpu_nap() may hang indefinitely. This was seen in practice in netfront_reset() when running in a VM on XenServer.
Fix this by skipping the halt if an EFI shutdown is in progress.
> [efi] Fix hang during ExitBootServices()

- src/include/ipxe/x509.h
- src/net/validator.c
Certificates issued by Let's Encrypt have two options for their chain of trust: the chain can either terminate in the self-signed ISRG Root X1 root certificate, or in an intermediate ISRG Root X1 certificate that is signed in turn by the self-signed DST Root CA X3 root certificate.  This is a historical artifact: when Let's Encrypt first launched as a project, the chain ending in DST Root CA X3 was used since existing clients would not have recognised the ISRG Root X1 certificate as a trusted root certificate.
The DST Root CA X3 certificate expired in September 2021, and so is no longer trusted by clients (such as iPXE) that validate the expiry times of all certificates in the certificate chain.
In order to maintain usability of certificates on older Android devices, the default …
> [crypto] Allow for multiple cross-signed certificate download attempts

- src/util/elf2efi.c
With this patch I can (cross-) compile ipxe for LoongArch UEFI with GCC 13.2 and binutils 2.41+ (and netboot LoongArch machines).
Several new relocations types have been added in LoongArch ABI version 2.10. In particular
- R_LARCH_B16 (18-bit PC-relative jump)
- R_LARCH_B21 (23-bit PC-relative jump)
- R_LARCH_PCREL20_S2 (22-bit PC-relative offset)
Also relocation relaxations have been introduced. Recent GCC (13.2) and binutils 2.41+ use these types of relocations, which confuses elf2efi tool. As a result ipxe EFI images for LoongArch fail to build with the following error:
```
make ARCH=loong64 CROSS_COMPILE=loongarch64-linux-gnu- bin-loong64-efi/ipxe.efi
[skipped lots of boring lines]
Unrecognised relocation type 103
```
To avoid the problem
- Ignore R_LARCH_B{16,21} and …
> elf2efi: ignore LoongArch PC-relative relocations and relaxations

- src/drivers/infiniband/golan.c
Fixing the issue https://github.com/ipxe/ipxe/issues/1091
Fix Eth inline header size to 14 bytes instead of 18 bytes. because the eapol packet is 18 bytes and all the packet was inserted to the inline header, so it appears as empty packet and the driver cant handle it.
Rabia manaa
rabiam@nvidia.com
> [golan.c] Fix inline header size

- src/drivers/net/efi/nii.c
- src/drivers/net/efi/snpnet.c
The Mellanox/Nvidia UEFI SNP driver is built from the same codebase as the iPXE driver, and appears to contain the bug that was fixed in commit c11734e ("[golan] Use ETH_HLEN for inline header size").  This results in identical failures when using the SNP interface (via e.g. snponly.efi) to drive a Mellanox card while EAPoL is enabled.
Work around the underlying UEFI SNP driver bug by padding transmit I/O buffers to the minimum Ethernet frame length before passing them to the underlying SNP driver's Transmit() function.
This padding is not technically necessary, since almost all modern hardware will insert transmit padding as necessary (and where the hardware does not support doing so, the underlying SNP driver is responsible for adding any necessary padding).  However, it is guaranteed …
> [snp] Pad transmit buffer length to work around buggy vendor drivers

- src/include/ipxe/settings.h
- src/net/netdev_settings.c
This PR continues the previous, accidentally closed PR https://github.com/ipxe/ipxe/pull/1047
Added a new setting that allows using this property in scripts. This can be useful in order to skip configuring
interfaces using their link layer protocol or, conversely, configure only selected interface type (Ethernet, IPoIB, etc.). In systems which have 8+ IB cards and one Eth card, this script can save 80+ seconds to boot by skipping await of IB's to be configured
Example script:
```
set idx:int32 0
:loop
isset ${net${idx}/mac} || exit 0
iseq ${net${idx}/ll-protocol} IPoIB && goto try_next ||
autoboot net${idx} ||
:try_next
inc idx && goto loop
```
> [netdevice] Add ll-protocol setting

- src/interface/efi/efi_veto.c
The reference implementation of Dhcp6Dxe in EDK2 has a fatal flaw: the code in EfiDhcp6Stop() will poll the network in a tight loop until either a response is received or a timer tick (at TPL_CALLBACK) occurs.  When EfiDhcp6Stop() is called at TPL_CALLBACK or higher, this will result in an endless loop and an apparently frozen system.
Since this is the reference implementation of Dhcp6Dxe, it is likely that almost all platforms have the same problem.
Fix by vetoing the broken driver.  If the upstream driver is ever fixed and a new version number issued, then we could plausibly test against the version number exposed via the driver binding protocol.
Fixes: #1192
> [efi] Veto the Dhcp6Dxe driver on all platforms

- src/include/ipxe/in.h
- src/include/ipxe/ip.h
- src/net/ipv4.c
In a small subnet (with a /31 or /32 subnet mask), all addresses within the subnet are valid host addresses: there is no separate network address or directed broadcast address.
The logic used in iPXE to determine whether or not to use a link-layer broadcast address will currently fail in these subnets.  In a /31 subnet, the higher of the two host addresses (i.e. the address with all host bits set) will be treated as a broadcast address.  In a /32 subnet, the single valid host address will be treated as a broadcast address.
Fix by adding the concept of a host mask, defined such that an address in the local subnet with all of the mask bits set to zero represents the network address, and an address in the local subnet with all of the mask bits set to one represents the directed broadcast …
> [ipv4] Support small subnets with no directed broadcast address

- src/include/ipxe/dhcpv6.h
- src/net/ndp.c
- src/net/udp/dhcpv6.c
The DHCPv6 protocol does not itself provide a router address or a prefix length.  This information is instead obtained from the router advertisements.
Our IPv6 minirouting table construction logic will first construct an entry for each advertised prefix, and later update the entry to include an address assigned within that prefix via stateful DHCPv6 (if applicable).
This logic fails if the address assigned via stateful DHCPv6 does not fall within any of the advertised prefixes (e.g. if the network is configured to use DHCPv6-assigned /128 addresses with no advertised on-link prefixes).  We will currently treat this situation as equivalent to having a manually assigned address with no corresponding router address or prefix length: the routing table entry will use the default /64 prefix …
> [ipv6] Expose router address for DHCPv6 leased addresses

- src/drivers/net/ena.c
- src/drivers/net/ena.h
As described in commit 3b81a4e ("[ena] Provide a host information page"), we currently report an operating system type of "Linux" in order to work around broken versions of the ENA firmware that will fail to create a completion queue if we report the correct operating system type.
As of September 2024, the ENA team at AWS assures us that the entire AWS fleet has been upgraded to fix this bug, and that we are now safe to report the correct operating system type value in the "type" field of struct ena_host_info.
The ENA team has also clarified that at least some deployed versions of the ENA firmware still have the defect that requires us to report an operating system version number of 2 (regardless of operating system type), and so we continue to report ENA_HOST_INFO_VERSION_WTF in the …
> [ena] Change reported operating system type to "iPXE"

- src/drivers/net/gve.c
The startup process is scheduled to run when the device is opened and terminated (if still running) when the device is closed.  It assumes that the resource allocation performed in gve_open() has taken place, and that the admin and transmit/receive data structure pointers are therefore valid.
The process initialisation in gve_probe() erroneously calls process_init() rather than process_init_stopped() and will therefore schedule the startup process immediately, before the relevant resources have been allocated.
This bug is masked in the typical use case of a Google Cloud instance with a single NIC built with the config/cloud/gce.ipxe embedded script, since the embedded script will immediately open the NIC (and therefore allocate the required resources) before the scheduled process is …
> [gve] Run startup process only while device is open

- src/crypto/rbg.c
- src/include/ipxe/rbg.h
The ANS X9.82 specification implicitly assumes that the RBG_Startup function will be called before it is needed, and includes checks to make sure that Generate_function fails if this has not happened. However, there is no well-defined point at which the RBG_Startup function is to be called: it's just assumed that this happens as part of system startup.
We currently call RBG_Startup to instantiate the DRBG as an iPXE startup function, with the corresponding shutdown function uninstantiating the DRBG.  This works for most use cases, and avoids an otherwise unexpected user-visible delay when a caller first attempts to use the DRBG (e.g. by attempting an HTTPS download).
The download of autoexec.ipxe for UEFI is triggered by the EFI root bus probe in efi_probe().  Both the root bus probe and …
> [crypto] Start up RBG on demand if needed

- src/hci/commands/dynui_cmd.c
- src/hci/tui/menu_ui.c
- src/include/ipxe/dynui.h
Allow the "--retimeout" option to be used to specify a timeout value that will be (re)applied after each keypress activity.  This allows script authors to ensure that a single (potentially accidental) keypress will not pause the boot process indefinitely.
Fixes: #1412
> [menu] Allow a post-activity timeout to be defined

- src/drivers/net/bnxt/bnxt.h
Add a wait  when buffers are not available for TX. Execute a PCI read to flush pending transactions when the condition is detected. Increase buffer and descriptor counts.
> [bnxt] Add a delay when Tx buffers are not available
